import "./globals.css";
import { NavBar } from "./components/ui/NavBar";
import { Contact } from "./components/Contact";
import { Inter, Sen } from "next/font/google";  

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const sen = Sen({
  subsets: ["latin"],
})

export const metadata = {
  title: "FBCFI Edmonton",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} ${sen.className} antialiased min-h-screen`} >
        <NavBar />

        <main>
            {children}
        </main>

        <Contact />
      </body>
    </html>
  );
}
