import "./globals.css";
import { NavBar } from "./components/ui/NavBar";
import { Contact } from "./components/Contact";
import { Montserrat , Karla } from "next/font/google";  

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: '--font-montserrat'
});

const karla = Karla({
  subsets: ["latin"],
})

export const metadata = {
  title: "FBCFI Edmonton",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${montserrat.variable} ${karla.className} antialiased min-h-screen`} >
        <NavBar />

        <main>
            {children}
        </main>

        <Contact />
      </body>
    </html>
  );
}
